name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    # New step to list JAR files in build/libs
    - name: List JAR files in build/libs
      run: ls build/libs/

    # Updated step to copy JAR file using a wildcard
    - name: Copy JAR file to Docker context
      run: cp build/libs/*.jar ./docker-context/

    - name: Build and Push Docker Image
      run: |
        docker build -t bruklemma/java-demo-app ./docker-context
        docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push bruklemma/java-demo-app
