# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build-java:
  
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew build
      working-directory: /home/demousr/actions-runner/_work/java-gradle-project/java-gradle-project/
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v2
      with:
        name: gradleartifact  
        path: /home/demousr/actions-runner/_work/java-gradle-project/java-gradle-project/build/libs/*.jar 
    - name: Run tests
      run: ./gradlew test  
    - name: Archive test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: build/reports/tests

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t mydockerimage .
  
    
    - name: Tag Docker image
      run: docker tag mydockerimage ${{ secrets.DOCKER_REPO }}:${GITHUB_RUN_NUMBER}
         
    - name: Push Docker image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_REPO }}:${GITHUB_RUN_NUMBER}
