# This workflow will build a docker container, publish it to Google Container Registry, and Deploy it to GKE when a release is created

name: Build and Sonar

on:
  push:
    branches:
      - 'master'


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
 - name: Grant execute permission for gradlew
      run: |
          cd sonarqube-scanner-gradle/gradle-basic/ 
          ls 
          chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build 
    - name: sonar test cases sent
      run: ./gradlew sonarqube  -Dsonar.projectKey=Test-java -Dsonar.host.url=http://34.102.242.212 -Dsonar.login=00f36a1c5f11cba114b458c538f292c196f1d103


   
