# This workflow will build a docker container, publish it to Google Container Registry, and Deploy it to GKE when a release is created

name: Build and Sonar

on:
  push:
    branches:
      - 'master'


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GCP_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   
