name: Lint and Format Code

on:
  push:
    paths:
      - 'src/python/**'
      - '.github/workflows/lint.yml'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint

    - name: Format code with Black
      run: black .

    - name: Run pylint
      id: lint
      continue-on-error: true
      run: pylint ./**/**.py > pylint_report.txt
    
    - name: Send code rating to slack
      run: |
        RATING=$(grep -oP "Your code has been rated at \K[0-9\.]+/[0-9\.]+" pylint_report.txt)
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Your code rating of your recent push is: ${RATING}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Extract error message
      id: extract_error
      run: |
        ERROR_MSG=$(grep -E "E[0-9]+" pylint_report.txt)
        echo "ERROR_MSG=${ERROR_MSG}" >> $GITHUB_ENV
          

    - name: Send custom JSON data to Slack workflow using original actions
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "Pylint score",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Pylint found the following errors:\n```${{ env.ERROR_MSG }}```"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
