name: OWASP ZAP Scan

on:
  push:
    branches:
      - master

jobs:
  owasp_zap_scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  
      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: Start web application
        run: |

           java -jar build/libs/java-app-1.0-SNAPSHOT.jar & # For example, if your application is a Spring Boot app:
    
      - name: Wait for application to start
        run: sleep 30

      - name: Download and run OWASP ZAP Docker container
        run: |
          docker pull owasp/zap2docker-stable
          docker run --name zap1 -u zap -p 8080:8080 -d owasp/zap2docker-stable

      - name: Run ZAP Spider and Active Scan
        run: |
          docker exec zap zap-cli --url http://20.192.4.51:8000 -p 8080 -I
          docker exec zap zap-cli --url http://20.192.4.51:8000 -p 8080 -c ascan -r '.*' -l High -I

      - name: Export ZAP Report
        run: |
          docker exec zap zap-cli report -o /zap/report.html -f html

      - name: Save ZAP Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: /zap/report.html

      - name: Stop and remove ZAP Docker container
        run: docker stop zap && docker rm zap